spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  datasource:
    write:
      jdbc-url: jdbc:postgresql://postgres-write:5432/bank_write
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    read:
      jdbc-url: jdbc:postgresql://postgres-read:5432/bank_read
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver

kafka:
  bootstrap-servers: localhost:9092
  topic:
    events: account-events
  consumer:
    group-id: balance-projector-group

server:
  port: 8080