spring:
  datasource:
    read:
      jdbc-url: jdbc:postgresql://localhost:5433/bank_read
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver

app:
  datasource:
    write:
      jdbc-url: jdbc:postgresql://localhost:5432/bank_write
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver

kafka:
  bootstrap-servers: localhost:9092
  topic:
    events: account-events
  consumer:
    group-id: balance-projector-group

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

server:
  port: 8080
